### ISSUE TITLE
Public Site Down?

### ISSUE THREAD

**Issue by Dibucci** [Artiexli/machine_pianist#2]
is the website down rn?
![image](https://github.com/ArthurlotLi/machine_pianist/assets/25534395/daa9e255-c248-496d-b350-fe400f9cd613)
I've been trying over and over with different Midi files but keep getting that same popup and nothing happens... I can listen to the ones that are in the site already but trying to upload midi's is not working?

**Comment by GeekPfs** [comment]
The same happened to me.

**Comment by ArthurlotLi** [comment]
Hi folks, the issue should be resolved now! Thanks for bringing this up, please let me know of any further issues.

**Comment by peterwang1996** [comment]
It seems to be not working again
![image](https://github.com/ArthurlotLi/machine_pianist/assets/12966803/32eab2b3-e4ba-4aa8-9410-90777cb047e8)

**Comment by liledix4** [comment]
Yes, the website still doesn't work, @ArthurlotLi
